/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

                export interface IsUserExistByLoginOrEmailRequest {
                  login?: string;
                  email?: string;
                }
                export interface IsUserExistByLoginOrEmailResponse {
                  result?: boolean;
                }
                export interface UserService {
                    isUserExistByLoginOrEmail(
                    data: IsUserExistByLoginOrEmailRequest,
                    metadata?: Metadata,
                    ...rest: any[]
                    ): Observable<IsUserExistByLoginOrEmailResponse>;
                }
    
